errno-list: don't use strerrorname_np() on glibc older than 2.32
strerrorname_np() was added in glibc-2.32, but errno_name_no_fallback()
used it whenever __GLIBC__ is defined, breaking the build on older
glibc (e.g. the oss-fuzz/ClusterFuzzLite images, glibc-2.31):

  ../src/basic/errno-list.c:32:16: error: implicit declaration of function 'strerrorname_np'

Fall back to the generated errno name table (already used for
non-glibc) in that case.